### ISSUE TITLE
Long title issue on mobile view

### ISSUE THREAD

**Issue by mylastore** [ryanwellsdotcom/jquery.responsive-tables#1]
![bug](https://user-images.githubusercontent.com/8906338/35760337-573ad8f6-0834-11e8-88e0-a475fbb5e1da.png)
Since the head titles are absolute when it runs out of space it breaks on top of the next heading title.

**Comment by ryanwellsdotcom** [comment]
I've pushed an interim fix. Let me know what you think.

**Comment by Kristinita** [comment]
@ryanwellsdotcom ,

### 1. Summary

I think, that **8d9342db8e1e0198ca2d848823cac0797301648a** is a bad commit.

`padding-bottom` can solve this problem.

### 2. Example of expected behavior

1. Revert **8d9342db8e1e0198ca2d848823cac0797301648a**.
1. **And**:

    1. Automatically add padding-bottom for text inside `th`.
    1. If action from 1.1 is hard, add option `padding-bottom` with default value `2rem`. Users can have different font size and headers length; we need give an opportunity select `padding-bottom` for each specific table.

### 3. Default settings

#### 3.1. Data

My example table.

+ [**Sources on Codepen**](https://codepen.io/Kristinita/pen/PrjGaE)

```html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-responsive-tables/js/jquery.responsive-tables.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-responsive-tables/css/responsive-tables.min.css" />
<table>
    <thead>
        <th>Kira very very long header</th>
        <th>Kira another very very long header</th>
    </thead>
    <tbody>
        <tr>
            <td>A1</td>
            <td>A2</td>
        </tr>
        <tr>
            <td>B1</td>
            <td>B2</td>
        </tr>
    </tbody>
</table>
```

```stylus
body
    font-size 2rem

table
    width 100%

/*
Disable border for demo
*/
.jrt td
    border-bottom-width 0 !important

```

```coffee
$(document).ready ->
    $.responsiveTables()
    return
```

#### 3.2. Result

+ [**Live demo on Codepen**](https://codepen.io/Kristinita/full/PrjGaE)

Header doesn't display fully.

![Non-expected result](https://i.imgur.com/sweWIRa.png)

### 4. Expected settings

#### 4.1. Data

+ [**Sources on Codepen**](https://codepen.io/Kristinita/pen/ZdyOBX)

I add to previous table:

```stylus
/*
* Words wrap in cells of HTML tables:
* https://stackoverflow.com/a/1539167/5951529
* https://caniuse.com/#search=break-all
*/
td
th
    word-break break-all

@media screen and (max-width 800px)

    for column in 1..2
        td.jrt-cell-{column}
            margin-bottom 4rem
            /*
            Line breaking for “content” CSS property:
            https://alligator.io/css/line-break-content-property/
            */
            &::before
                white-space normal !important
```

#### 4.2. Result

+ [**Live demo on Codepen**](https://codepen.io/Kristinita/full/ZdyOBX)

![Expected result](https://i.imgur.com/nc07pE8.png)

Thanks.

**Comment by ryanwellsdotcom** [comment]
This has been resolved and the fixed is pushed and the demo has been updated as well. I've tested this in all major browsers back to IE11. Sorry about the delay.
